# Generated by Django 5.0.6 on 2024-07-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_is_online_userstatus_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
