# Generated by Django 5.0.6 on 2024-07-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
