# Generated by Django 5.0.6 on 2024-07-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
