# Generated by Django 5.0.6 on 2024-08-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_userstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
